name: crs_backend

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: crs_wordpress
    restart: always
    volumes:
      - ./wp_data:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: crssite
    ports:
      - 8585:80

  db:
    image: mariadb:lts
    container_name: crs_mariadb
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
      #- ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
      MYSQL_DATABASE: crssite
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: crs_phpmyadmin
    restart: always
    ports:
      - 8686:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
      UPLOAD_LIMIT: 1G
